### ISSUE TITLE
export 'signERC2612Permit' not found in 'eth-permit'

### ISSUE THREAD

**Issue by eabdelmoneim** [thirdweb-dev/typescript-sdk#143]
Client "whop" is running into this error compiling with the sdk

![Screen Shot 2021-12-28 at 8 45 30 AM](https://user-images.githubusercontent.com/10700302/147578132-c8563a9f-a5c6-4470-9531-cd516bf6480c.png)

**Comment by atbe** [comment]
@jnsdls assigning this to you because you kindly offered to court the Whop team on the 1pm PST call today, tyvm! Let us know how it goes. We should use this ticket to aggregate all the info around this bug to make hand-offs easier.

CC @adam-maj  who tried to help out here a bit.
