### ISSUE TITLE
Resolve ENS addresses on snapshot

### ISSUE THREAD

**Issue by nachoiacovino** [thirdweb-dev/typescript-sdk#181]
When creating snapshots, we should try to resolve ens names to their true address.

This is the segment of code where we process the addresses: https://github.com/nftlabs/nftlabs-sdk-ts/blob/main/src/core/index.ts#L524

As you can see, the addresses are passed-as is.

The tests we need for this ticket:
- [x] Passing in an ENS address when creating a snapshot results in the resolved address being added to the snapshot
- [x] All addresses passed to the `createSnapshot` function should be lowercased

We have more enhancements coming to the snapshot module, but lets keep the tickets lean so this one only accomplishes the above two goals.

**Comment by jakeloo** [comment]
@atbe @ayshptk  let's punt on this for now. we should leave resolving we need an rpc connection to mainnet and we need to deal with the rpc rate limit.
