### ISSUE TITLE
Provide an event based mechanism for retrieving transaction receipts on transactions

### ISSUE THREAD

**Issue by atbe** [thirdweb-dev/typescript-sdk#20]
i think currently, most write methods return TransactionReceipt if void.
for a reason that people can keep track of the hashes offchain or do further processing.

in general, i think we need to have a better system in the SDK for TransactionReceipt, i feel like we should almost have a `.on('transactionSent', (transactionReceipt) => void)` event in the SDK so people can subscribe for these tx receipt. (for future notes)

_Originally posted by @jakeloo in https://github.com/nftlabs/nftlabs-sdk-ts/pull/19#discussion_r747009111_

**Comment by atbe** [comment]
@jakeloo  so I don't think this should block the royalty module unless we feel like we *absolutely* need to return this info in the current iteration.

**Comment by jakeloo** [comment]
nope. it's not blocking.
