### ISSUE TITLE
"buy" action in dashboard is throwing error

### ISSUE THREAD

**Issue by eabdelmoneim** [thirdweb-dev/typescript-sdk#228]
https://thirdweb.com/mumbai/0x2D502F5C8Da741FC572D5D2CB113Cd77355e4d33/market/0xc1B5eBBCe602c2079ac967aB12eddDa4Cf4aFE8D

exception:
![Screen Shot 2022-01-24 at 11 03 37 AM](https://user-images.githubusercontent.com/10700302/150837273-a7faa811-d921-4cf9-8dfa-5f1c41ee3430.png)

**Comment by atbe** [comment]
@ayshptk can you look into this please?
