### ISSUE TITLE
"Api Reference and code examples" link broken

### ISSUE THREAD

**Issue by saricden** [thirdweb-dev/typescript-sdk#275]
The link shown below, entitled "Api Reference and code examples", for the new SDK is going to a 404 page:

![Screenshot from 2022-03-04 04-09-41](https://user-images.githubusercontent.com/7004280/156761256-1a4246bd-2830-40f2-a2a1-377646f79656.png)

**Comment by ericauv** [comment]
Appears to be solved -- links to https://typescript-docs.thirdweb.com/ now

**Comment by warengonzaga** [comment]
@joaquim-verges kindly close thanks!
