### ISSUE TITLE
getAllListings returns listings even which are sold

### ISSUE THREAD

**Issue by chaitak-gorai** [thirdweb-dev/typescript-sdk#332]
I was using thirdweb in a project and  have call "getAllListings"  but it returns all listing history not only the realtime listed.

So, can anyone give a solution to this problem?? Like how can i only get the realtime listed nfts..??

Please Help!!

Thank You

**Comment by jnsdls** [comment]
hey @chaitak-gorai, it sounds `getActiveListings()` is likely what you're looking for:

https://docs.thirdweb.com/typescript/sdk.marketplace.getactivelistings#marketplacegetactivelistings-method

**Comment by chaitak-gorai** [comment]
Hello @jnsdls thanks for the fast reply, i didn't find this earlier in docs. Now also it is giving error. 
![image](https://user-images.githubusercontent.com/77141674/161384626-191fe38c-db16-4223-a5ff-1ea47f136e8d.png)

it might be due to the version difference. If yes, can u specify the latest version to use this function?

**Comment by jnsdls** [comment]
@chaitak-gorai that looks like you might be using `v1` sdk? could you check the version of `@thirdweb-dev/sdk` in your package json and make sure it is at least `2.x.x`?

**Comment by chaitak-gorai** [comment]
yeah, i m using version **v1** sdk , got the error. I have to upgrade it to  v2.
Thanks man!

**Comment by jnsdls** [comment]
happy we figured it out! closing :)
