### ISSUE TITLE
Failed to set claim condition Error: Status code (!= 200) =403

### ISSUE THREAD

**Issue by giserman** [thirdweb-dev/typescript-sdk#353]
In Buildspace Dao project，When using metadata.get() or claim Conditions.set to send a request, the same error is returned, the details are shown in the figure
![unknown](https://user-images.githubusercontent.com/6097474/164653077-c3d14740-7e3a-4fc6-900c-351f5b4d4535.png)
<img width="601" alt="Screen_Shot_2022-04-20_at_3 19 17_PM" src="https://user-images.githubusercontent.com/6097474/164653239-98b8caf9-c7ea-4a22-9656-5130754f7578.png">

**Comment by joaquim-verges** [comment]
@giserman we had some downtime with our ipfs gateway, should be resolved now. let me know if it works!

**Comment by giserman** [comment]
the issue  is not solved. It's the same mistake
