### ISSUE TITLE
[Bug]: ThirdWeb SDK crashes SvelteKit page because of using undefined "globals".

### ISSUE THREAD

**Issue by skoshx** [thirdweb-dev/typescript-sdk#458]
**Prerequisites**

* [x] I have checked that `@thirdweb-dev/sdk` is on the latest _stable_ version and the bug still exists.
* [x] I have checked [existing issues](https://github.com/thirdweb-dev/typescript-sdk/issues?q=is%3Aissue) and I was unable to find a duplicate of this.

**Optional**

* [ ] I am willing to contribute a PR that fixes the problem with some guidance.

**Describe the bug**
When using `@thirdweb-dev/sdk` in SvelteKit (in browser context), it causes the page to crash by simply importing the library:

```typescript
import { ThirdwebSDK } from "@thirdweb-dev/sdk";

// this is all that's needed to crash the page.
```

This happens because ThirdwebSDK uses "globals" that seem to be polyfilled in other frameworks but isn't the case with SvelteKit (or maybe Vite)

**Expected behavior**
Expected to work in browser.

**Screenshots**

<img width="1193" alt="Screenshot 2022-06-07 at 16 45 34" src="https://user-images.githubusercontent.com/16806818/172396122-15c1deb8-5850-4871-944e-b1cf9c482e62.png">

**Package versions (please complete the following information):**
 - `@thirdweb-dev/sdk`: [2.3.7]
 - `node`: [v16.13.0]
 - `typescript` (if applicable): [e.g. 3.8.3] 
 - Any other build tools (`react`, `next`, `angular`, `vue`, etc.): [e.g. v12.16.3]

**Reproduction link**

[Minimal reproduction](https://github.com/skoshx/thirdweb-sdk-repro)

**Additional context**

**Comment by jnsdls** [comment]
hey @skoshx, thanks for the reproduction case! we'll take a look at it and will hopefully be able to fix it quickly, if we need further information we'll ask here.

**Comment by jnsdls** [comment]
@skoshx this should be fixed in https://github.com/thirdweb-dev/typescript-sdk/releases/tag/v2.3.8

**Comment by skoshx** [comment]
@jnsdls Works like a charm! Thanks for the quick fix!
