### ISSUE TITLE
[Bug]: `marketplace.getAllListings()` spews out unsupressable warning logs

### ISSUE THREAD

**Issue by skoshx** [thirdweb-dev/typescript-sdk#495]
**Prerequisites**

* [x] I have checked that `@thirdweb-dev/sdk` is on the latest _stable_ version and the bug still exists.
* [x] I have checked [existing issues](https://github.com/thirdweb-dev/typescript-sdk/issues?q=is%3Aissue) and I was unable to find a duplicate of this.

**Optional**

* [ ] I am willing to contribute a PR that fixes the problem with some guidance.

**Describe the bug**
When calling `.getAllListings()`, it spits out a bunch of warning logs like "Error fetching listing with id: 2 ListingNotFoundError: Could not find listing. marketplace address: 0x97164BdA5eD158873CA2E696cEBf7AFC04cC5445 listing id: 2".

These warnings are not relevant for me, so I would like to suppress them so they don't pollute my actual error logs, however, I cannot get these warnings to stop logging with anything. I think there should be some logging options for ThirdwebSDK.

The problem stems from these lines in `marketplace.ts`:

```typescript
try {
  listing = await this.getListing(i);
} catch (err) {
  console.warn(`Error fetching listing with id: ${i}`, err);
  return undefined;
}
```

**Expected behavior**

**Screenshots**

**Package versions (please complete the following information):**
 - `@thirdweb-dev/sdk`: [^2.3.11]
 - `node`: [v16.13.0]
 - `typescript` (if applicable): [e.g. 3.8.3] 
 - Any other build tools (`react`, `next`, `angular`, `vue`, etc.): [e.g. v12.16.3]

**Reproduction link**
```typescript
const { ThirdwebSDK } = require('@thirdweb-dev/sdk');
const sdk = new ThirdwebSDK('mumbai');
const contract = sdk.getMarketplace('0x97164BdA5eD158873CA2E696cEBf7AFC04cC5445');

// this prints out the logs
const listings = await contract.getAllListings();
```

**Additional context**

**Comment by ndeto** [comment]
Hi @skoshx , Kindly update your SDK version to the latest stable version. That should resolve your issue.
